controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    amr_controller:
      type: 4wd_diff_drive_controller/4wdDiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


amr_controller:
  ros__parameters:
    type        : 4wd_diff_drive_controller/4wdDiffDriveController
    use_stamped_vel: true
    rear_left_wheel_names  : ['wheel_rear_left_joint']
    rear_right_wheel_names : ['wheel_rear_right_joint']
    front_left_wheel_names  : ['wheel_front_left_joint']
    front_right_wheel_names : ['wheel_front_right_joint']

    publish_rate: 50.0               # default: 50
    pose_covariance_diagonal : [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_separation_lr : 0.17
    wheel_separation_fr : 0.17
    wheel_radius : 0.033

    wheel_separation_lr_multiplier: 1.0
    wheel_separation_fr_multiplier: 1.0
    rear_left_wheel_radius_multiplier: 1.0
    raer_right_wheel_radius_multiplier: 1.0
    front_left_wheel_radius_multiplier: 1.0
    front_right_wheel_radius_multiplier: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.5

    # Base frame_id
    base_frame_id: base_footprint #default: base_link

    # Publish limited velocity
    publish_limited_velocity: true

    # Publish wheel data
    publish_wheel_data: true

    # Publish to TF directly or not
    enable_odom_tf: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0  # m/s
        min_velocity           : -0.5 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.8  # m/s^2
        min_acceleration       : -0.4 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.7  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 1.5  # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 2.5  # rad/s^3


simple_velocity_controller:
  ros__parameters:
    joints:
      - wheel_rear_left_joint
      - wheel_rear_right_joint
      - wheel_front_left_joint
      - wheel_front_right_joint